apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 4
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: py-consumer-image:latest
        imagePullPolicy: Never
        env:
        - name: RABBITMQ_HOST
          value: rabbitmq
        volumeMounts:
        - name: data-volume
          mountPath: "/data"
        - name: data-output
          mountPath: "/output"
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: my-pvc
      - name: data-output
        hostPath:
          path: /run/desktop/mnt/host/d/data
          type: Directory
